Repository Washi1337/AsmResolver, pull requests merged in 2024-05, with the labels that each got.

#555 Set Accessors for Semantic Methods
  src/AsmResolver.DotNet/EventDefinition.cs
  src/AsmResolver.DotNet/PropertyDefinition.cs
  test/AsmResolver.DotNet.Tests/PropertyDefinitionTest.cs
Labels: enhancement, dotnet

#544 MemoryMappedFile for .NET Framework 3.5
  src/AsmResolver/AsmResolver.csproj
  src/AsmResolver/IO/ByteArrayInputFile.cs
  src/AsmResolver/IO/IInputFile.cs
  src/AsmResolver/IO/MemoryMappedDataSource.cs
  src/AsmResolver/IO/MemoryMappedFileService.cs
  src/AsmResolver/IO/MemoryMappedInputFile.cs
  src/AsmResolver/Shims/MemoryMappedFileShim.Unix.cs
  src/AsmResolver/Shims/MemoryMappedFileShim.Windows.cs
  src/AsmResolver/Shims/MemoryMappedFileShim.cs
  test/AsmResolver.Tests/IO/MemoryMappedIOTest.cs
Labels: enhancement

#557 Address several issues with reading specially crafted .NET metadata
  .editorconfig
  src/AsmResolver.DotNet/Builder/DotNetDirectoryFactory.cs
  src/AsmResolver.DotNet/Builder/Metadata/Tables/TablesStreamBuffer.cs
  src/AsmResolver.DotNet/Builder/MetadataBuilderFlags.cs
  src/AsmResolver.PE/DotNet/Metadata/DefaultMetadataStreamReader.cs
  src/AsmResolver.PE/DotNet/Metadata/IMetadataStreamReader.cs
  src/AsmResolver.PE/DotNet/Metadata/MetadataStreamList.cs
  src/AsmResolver.PE/DotNet/Metadata/MetadataStreamReaderFlags.cs
  src/AsmResolver.PE/DotNet/Metadata/SerializedMetadata.cs
  src/AsmResolver.PE/DotNet/Metadata/Tables/IMetadataTable.cs
  src/AsmResolver.PE/DotNet/Metadata/Tables/IndexEncoder.cs
  src/AsmResolver.PE/DotNet/Metadata/Tables/MetadataTable.cs
  src/AsmResolver.PE/DotNet/Metadata/Tables/SerializedTableStream.cs
  src/AsmResolver.PE/DotNet/Metadata/Tables/TablesStream.cs
  test/AsmResolver.DotNet.Tests/Builder/ManagedPEImageBuilderTest.cs
  test/AsmResolver.DotNet.Tests/Properties/Resources.Designer.cs
  test/AsmResolver.DotNet.Tests/Properties/Resources.resx
  test/AsmResolver.DotNet.Tests/Resources/HelloWorld.JTDStream.exe
  test/AsmResolver.PE.Tests/DotNet/Metadata/MetadataTest.cs
  test/AsmResolver.PE.Tests/Properties/Resources.Designer.cs
  test/AsmResolver.PE.Tests/Properties/Resources.resx
  test/AsmResolver.PE.Tests/Resources/HelloWorld.JTDStream.exe
  test/AsmResolver.PE.Tests/Resources/HelloWorld.LowerCaseHeapsNormalMetadata.exe
  test/AsmResolver.PE.Tests/Resources/HelloWorld.LowerCaseHeapsWithEnC.exe
  test/AsmResolver.PE.Tests/Resources/HelloWorld.SchemaStream.exe
Labels: bug, pe
